### ISSUE TITLE
无限更新

### ISSUE THREAD

**Issue by shi-an** [mo-jinran/LiteLoaderQQNT-Plugins-Marketplace#16]
插件更新重启后依旧要更新

**Comment by mo-jinran** [comment]
具体是什么插件？无法复现
不过之前确实有个插件会导致无限更新，这属于插件的问题

**Comment by shi-an** [comment]
插件市场

**Comment by yige-yigeren** [comment]
> 具体是什么插件？无法复现 不过之前确实有个插件会导致无限更新，这属于插件的问题

似乎自更新有些问题，无法更新，重启后插件市场仍需要更新

**Comment by Winter-is-comingXK** [comment]
我也遇到了
![QQ_8MQERt5jo4](https://github.com/mo-jinran/LiteLoaderQQNT-Plugins-Marketplace/assets/33370220/10a3e2d3-7b8b-4fb3-abbb-8b663cb3b5d7)

**Comment by mo-jinran** [comment]
已修复
